name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.PRIVATE_SSH_KEY }}

          script: |
            # переходимо в папку проєкту на VPS
            cd /opt/fateforge-arena

            # тягнемо останні зміни з GitHub
            git pull origin main

            # оновлюємо тільки Node.js API сервіс
            docker compose -f docker-compose.prod.yml up -d --build api

            # # застосовуємо Prisma міграції
            # docker exec api_prod npx prisma migrate deploy --config=dist/prisma.config.ts

            # застосовуємо Prisma міграції
            docker exec api_prod yarn prisma:deploy

            # # створення адміна
            # docker exec api_prod node dist/prisma/seeds/admin.seed.js

            # створення адміна
            docker exec api_prod node prisma/seeds/admin.seed.js

            # очищення старих Docker image шарів
            docker image prune -f
