name: CI Pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - run: yarn install --frozen-lockfile
      - run: yarn test

  build:
    name: Build
    needs: [unit-tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - run: yarn install --frozen-lockfile
      - run: yarn build
